### PR TITLE
fix(docs2md): 404 should not log an error (#84)

### LINKED ISSUE #84: 404 should not log an error
a request to non existing document shows an error in the logs:

```
{
   "level"  :  "error" ,
   "ow"  : {
     "activationId"  :  "1d6fa83424cc4ca3afa83424cc3ca3fa" ,
     "actionName"  :  "/helix/helix-services-private/gdocs2md@1.3.2" ,
     "transactionId"  :  "hlIwvDNj5cV3sYTIa8LILbSAb0b1KX7s" 
  },
   "message"  :  "error while converting document: Error: Not Found: /head" ,
   "timestamp"  :  "2019-10-23T23:11:07.244Z" 
}
```

IMO, only failures of the service should be logged as error.

### PR DESCRIPTION
**Pull request by rofe**
Fix #84

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -111,31 +111,42 @@ async function fetchViaAPI(params) {
...
+      statusCode: 200,
+      body: md,
+      headers: {
+        'Content-Type': 'text/plain',
+        'Content-Length': md.length,
+        'Cache-Control': 'no-store, private, must-revalidate',
+      },
+    };
+  } catch (e) {
+    log[e.statusCode >= 500 ? 'error' : 'info']('error while converting document: %s', e);
```
Comment (tripodsan) [inline src/index.js]: what if `e` doesn't have a status code?

File: src/index.js [hunk 2]
```diff
@@ -144,13 +155,7 @@ async function fetchViaAPI(params) {
  * @returns {Promise<*>} The response
  */
 async function run(params) {
-  const { __ow_logger: log } = params;
-  try {
-    return await fetchViaAPI(params);
```
Comment (tripodsan) [inline src/index.js]: why did you move the try catch?

File: src/index.js (hunk 1 above)
Comment (rofe) [reply src/index.js]: Good point. I'll check for it.

Comment (rofe) [reply src/index.js]: Actually, then it would just produce an `info` log message, which I guess is appropriate.

File: src/index.js (hunk 2 above)
Comment (rofe) [reply src/index.js]: Because I found it better if `fetchViaAPI` would always return a response object and never throw, so its only caller `run` wouldn't have to catch it anymore.

Comment (rofe) [reply src/index.js]: I reverted it
